'use strict'
/* eslint-disable no-unused-vars */

var FETCH_BOOKS_REQUEST = 'FETCH_BOOKS_REQUEST'
var FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS'
var FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE'
var ADD_BOOK_REQUEST = 'ADD_BOOK_REQUEST'
var ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS'
var ADD_BOOK_FAILURE = 'ADD_BOOK_FAILURE'
